version: '3.2'

services:
  pccg-rs:
    image: docker.pkg.github.com/circlesabound/pccg-rs/pccg-rs:latest
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./secrets
        target: /secrets
    labels:
      - traefik.http.routers.pccg-rs.rule=PathPrefix(`/api/{version:v[0-9.]+}`)

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    # command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
