name: Publish to GitHub Docker Registry and deploy via SSH

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: pccg-rs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker build . \
            --file test.Dockerfile

  push:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == push
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build image
        run: |
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker build . \
            --file Dockerfile \
            --tag image \
            --build-arg GIT_COMMIT_HASH=$COMMIT_HASH

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=$(git rev-parse --short "$GITHUB_SHA")

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      name: Deploy using SSH
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: ~/deploy-latest.sh
